2022-08-16 08:11:14,155 ERROR c.r.u.ConnectionUtil [main] connection attemp error
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.Driver.makeConnection(Driver.java:400) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.Driver.connect(Driver.java:259) ~[postgresql-42.3.3.jar:42.3.3]
	at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:36) [classes/:?]
	at com.revature.dao.UserDaoImplementation.getUserByUsername(UserDaoImplementation.java:55) [classes/:?]
	at com.revature.services.UserService.createUser(UserService.java:47) [classes/:?]
	at com.revature.consoleviews.MainMenu.view(MainMenu.java:55) [classes/:?]
	at com.revature.App.main(App.java:33) [classes/:?]
Caused by: java.net.UnknownHostException: null
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:564) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.3.jar:42.3.3]
	... 11 more
2022-08-16 08:21:20,860 ERROR c.r.u.ConnectionUtil [main] connection attemp error
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.Driver.makeConnection(Driver.java:400) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.Driver.connect(Driver.java:259) ~[postgresql-42.3.3.jar:42.3.3]
	at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:36) [classes/:?]
	at com.revature.dao.UserDaoImplementation.getUserByUsername(UserDaoImplementation.java:55) [classes/:?]
	at com.revature.services.UserService.createUser(UserService.java:47) [classes/:?]
	at com.revature.consoleviews.MainMenu.view(MainMenu.java:55) [classes/:?]
	at com.revature.App.main(App.java:33) [classes/:?]
Caused by: java.net.UnknownHostException: null
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:564) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.3.jar:42.3.3]
	... 11 more
2022-08-16 19:40:13,487 INFO c.r.c.MainMenu [main] User askar successfully logged into system
2022-08-16 19:42:10,573 INFO c.r.c.MainMenu [main] User sezer successfully logged into system
2022-08-17 07:29:15,289 INFO c.r.c.MainMenu [main] User sezer successfully logged into system
2022-08-17 07:43:43,710 INFO c.r.c.MainMenu [main] User sezer successfully logged into system
2022-08-17 08:50:16,126 INFO c.r.c.MainMenu [main] User jhg successfully logged into system
2022-08-17 09:10:01,142 INFO c.r.c.MainMenu [main] User test successfully logged into system
